var myArray = ["Afina Razla Binti Afifuddin - Tiket # 4",
"Aida Farisa - Tiket # 227",
"Aila Haryati Harun Harashaid  - Tiket # 102",
"Aimi Syazwani Binti Zainuddin - Tiket # 238",
"Ainol Mardhiah Binti Mohd Khalid - Tiket # 186",
"Ani Bt Abdullah - Tiket # 180",
"Anul Suhada Abu Bakar - Tiket # 109",
"Asma Amira - Tiket # 165",
"Asmawati Binti Samsul - Tiket # 98",
"Azean Irdawaty Bt Md Noor - Tiket # 216",
"Azlinda Binti Alies - Tiket # 36",
"Azlinda Binti Hussin - Tiket # 38",
"Azmah Binti Hamzah - Tiket # 192",
"Azzura binti Abd Latif - Tiket # 166",
"Che Wan Rohata Binti Abdul Hamid - Tiket # 130",
"Diana Binti Seman - Tiket # 195",
"Dr. Norizah Binti Hj Ibrahim - Tiket # 77",
"Elena Sofia Elfera Mamat - Tiket # 230",
"Emmi Nur Sila Binti Adnan - Tiket # 8",
"Ewwa Bt Mohd Yusoff - Tiket # 182",
"Ezenti Rubiyani Binti Ismail - Tiket # 28",
"Fadhlul Jannah Abd Karim - Tiket # 107",
"Fadillah Abdul Rahman - Tiket # 231",
"Fadzilah Binti Salimin - Tiket # 58",
"Fara Shafiza Othman - Tiket # 140",
"Farahwahida Binti Anuar - Tiket # 71",
"Faridatul Najihah Binti Muhamad Ali - Tiket # 133",
"Farrah Wahida Haris - Tiket # 204",
"Farziliyatul Ashmar Izahar - Tiket # 241",
"Fatin Ajla Binti Khairy - Tiket # 62",
"Fatin atirah binti mahfudz - Tiket # 181",
"Fauzani Binti Azam - Tiket # 53",
"Fauziah binti Adam - Tiket # 74",
"Fazzida Binti Rosli - Tiket # 175",
"Fitriani Bakthiar - Tiket # 82",
"Habibah Bt Abdul Shukor - Tiket # 219",
"Hadiana Binti Ishak - Tiket # 183",
"Halimaton Mohd Rashid - Tiket # 60",
"Haryana Abdul Rahim - Tiket # 167",
"Haryani Binti Kaulan - Tiket # 205",
"Haslina Zakaria - Tiket # 228",
"Hasnah Binti Ghazali - Tiket # 124",
"Hazimah Binti Mustafa - Tiket # 6",
"Hazizah Binti Abdullah - Tiket # 13",
"Ili Ihsan Binti Zaidi - Tiket # 171",
"Intan Annisa - Tiket # 106",
"Intan Hafina - Tiket # 105",
"Intan Rayahin Bt. Hassan - Tiket # 213",
"Isma Hamiza Binti Ismail - Tiket # 46",
"Isniza Binti Nazerah - Tiket # 203",
"Iznina Hanim Binti Hashim - Tiket # 155",
"Julia Binti Abdul Razak - Tiket # 35",
"Juliyana Binti Burhan - Tiket # 67",
"Khairun Nisa Binti Bahari - Tiket # 116",
"Khalidah Adibah Khalid - Tiket # 138",
"Khatijah Binti Mohd - Tiket # 148",
"Kushamsinar - Tiket # 149",
"Maheran Binti Kasim - Tiket # 249",
"Mardiah Mohamed Saleh - Tiket # 137",
"Marina Binti Mansor - Tiket # 134",
"Marshitah Binti Omar - Tiket # 37",
"Marsyila Binti Masrom - Tiket # 190",
"Maryam Nazeera Binti Suhaimi  - Tiket # 18",
"Masitah Bt Mustapha  - Tiket # 233",
"Masni Binti Mohd Marzuki - Tiket # 142",
"Maziah Binti Moktar - Tiket # 81",
"Mazlina Abd. Karim - Tiket # 121",
"Mazliza Bt Abdul Wahid - Tiket # 250",
"Mazuin Binti Masuaud - Tiket # 61",
"Mimi Suzana Bt Mohd Rashid - Tiket # 245",
"Munirah Binti Osri - Tiket # 45",
"Nadia Binti Abd Aziz Karam Khan - Tiket # 65",
"Nadya Nikman - Tiket # 2",
"Nazira mustafa - Tiket # 7",
"Nazirah bt Abdullah - Tiket # 112",
"Noor Azrin bt Abdul Wahab - Tiket # 113",
"Noor Hafidza by. Sajuni - Tiket # 188",
"Noor Hafizoh Binti Saebon - Tiket # 97",
"Noor Hasliza Binti Mohd Rawi - Tiket # 242",
"Noor Juliana Binti Mohamad Jamal - Tiket # 194",
"Noor Munirah Binti Zainol Abidin - Tiket # 126",
"Noor Sadiqin Binti Azamuddin - Tiket # 214",
"Noor Shazleen Ishak - Tiket # 42",
"Noorainura Binti Mazlan - Tiket # 21",
"Noorawati Binti A. Rahim - Tiket # 31",
"Nor Aziati Jaafar - Tiket # 248",
"Nor Aziela Jamaluddin - Tiket # 87",
"Nor Azimah Binti Jamaluddin - Tiket # 125",
"Nor Azlan Binti Atan - Tiket # 143",
"Nor Azliza Rahman - Tiket # 222",
"Nor Azuma Binti Che Azmi - Tiket # 152",
"Nor Diana Binti Yahaya - Tiket # 25",
"Nor Diana Bt Azlan - Tiket # 136",
"Nor Hafizah Bt Zainol - Tiket # 117",
"Nor Hafizah Bt. Hashim - Tiket # 223",
"Nor Hanisah Binti Ishak - Tiket # 12",
"Nor Haniza Waty Khalil - Tiket # 78",
"Nor Haslina Muhamad - Tiket # 208",
"Nor Haslinda Mohd Harun - Tiket # 80",
"Nor Hidayu Binti Abdul Halim - Tiket # 172",
"Nor Khairunnisa Bt Johari - Tiket # 246",
"Nor Mah Ahmad - Tiket # 185",
"Nor Zawani Binti Hussain - Tiket # 26",
"Nora Azila Baharudin - Tiket # 224",
"Noraidah Binti Dolah - Tiket # 23",
"Norain Shakira Binti Mohd Salleh - Tiket # 243",
"Noraini Binti Mat Isa - Tiket # 173",
"Noraini binti Talib - Tiket # 118",
"Noraishah Rahimah Binti Omar - Tiket # 160",
"Norakmal Binti Mohd Punzan - Tiket # 122",
"Noraliza Binti Abdul Hamid - Tiket # 163",
"Noraziah Binti M Roshid - Tiket # 1",
"Norazrena Binti Halim - Tiket # 49",
"Norazura Binti Tambi@Yahaya - Tiket # 43",
"Norazwana Binti Aizon - Tiket # 3",
"Nordiana Binti Rozali - Tiket # 206",
"Norfaizah Binti Ghazaly - Tiket # 187",
"Norfaraziana Binti Minhat - Tiket # 174",
"Norhairiza Binti Mohd Ridzan - Tiket # 162",
"Norhaliza Binti Abu Bakar - Tiket # 9",
"Norhaliza binti Hanifah - Tiket # 232",
"Norhatini Binti Idris - Tiket # 14",
"Norhayati Binti Abd Malik - Tiket # 159",
"Norida Saidi Binti Abd Manaf - Tiket # 40",
"Norliana Akida Binti Abd Rahim - Tiket # 16",
"Norliyana Alias - Tiket # 30",
"Norliza Binti Bahsin@Zakaria - Tiket # 24",
"Norliza Binti Hood - Tiket # 86",
"Normala Hanim binti Abdul Hamid - Tiket # 115",
"Norsuzira Binti Setia - Tiket # 193",
"Norwahida bt Shuib - Tiket # 75",
"Norzaihan Binti Rohman - Tiket # 209",
"Norzalillah Binti Abdullah - Tiket # 20",
"Norzita Abd Razak - Tiket # 170",
"Nur `Izzan Fariha Ahmad Sabri - Tiket # 234",
"Nur Adibah Nabilah Binti Abu Bakar - Tiket # 244",
"Nur Aimuni Athirah Binti Omar - Tiket # 120",
"Nur Ain Bt Idris - Tiket # 215",
"Nur aisya yasmin binti mohd azmi - Tiket # 34",
"Nur Alia Binti Zarmani - Tiket # 240",
"Nur Amalina Abdullah Sawal - Tiket # 41",
"Nur Aqilah Binti Shamsuddin - Tiket # 22",
"Nur Asmira Binti Asmat - Tiket # 47",
"Nur Azianni Binti Abd Aziz - Tiket # 90",
"Nur Hafiza Binti Muhammad Azhari - Tiket # 33",
"Nur Halinna Binti Abdul Rahman - Tiket # 57",
"Nur Hidayatul Akhmal - Tiket # 146",
"Nur Huda Binti Abdul Hamid - Tiket # 29",
"Nur Khadeeja Humayraa Binti Mohd Azmi - Tiket # 154",
"Nur Malina bt Che Mohd Sukarhata - Tiket # 144",
"Nur Nazifah Mukhtar - Tiket # 39",
"Nur Ruzanna Binti Mohamad Allias - Tiket # 157",
"Nur Syafiqah Binti Azman - Tiket # 72",
"Nuraisyah Binti Abu Hassim - Tiket # 84",
"Nuramimah Binti Azahar - Tiket # 101",
"Nurhayati Binti Mohd Wahid - Tiket # 88",
"Nurhuwaina Bt Mohd Afandi - Tiket # 93",
"Nurrul Hafizah - Tiket # 104",
"Nurseha Binti Ramlee - Tiket # 10",
"Nurul Ain Shafini Binti Abdul Khalid - Tiket # 51",
"Nurul Aini Fazillah Binti Ahmad Taufik - Tiket # 44",
"Nurul Asyilah Binti Mohd Khalid - Tiket # 63",
"Nurul Hanim Zainudin - Tiket # 68",
"Nurul Hidayah Binti Mohamad@Mohd Khalid - Tiket # 79",
"Nurul Mardhiah Bt Mohammed Redza - Tiket # 247",
"Nurul Syafiqah Halim - Tiket # 225",
"Nurullizah Binti Jamaludin - Tiket # 212",
"Nurzulyna Binti Sani - Tiket # 76",
"Nuurul Aqmar Bt Ali - Tiket # 221",
"Poniah binti Badrul - Tiket # 237",
"Rahimah Binti Saidin - Tiket # 161",
"Rasmanizah Binti Che Rahim - Tiket # 127",
"Rizaiton Binti Khairuddin - Tiket # 132",
"Rohaidah Binti Mad Said - Tiket # 207",
"Rohanizawati Binti Hasni - Tiket # 50",
"Rosmawar binti Mahadi - Tiket # 128",
"Rosni Binti Ujang - Tiket # 94",
"Rus Ima Nadia Binti Hussain - Tiket # 64",
"Ruzana Che Soh - Tiket # 217",
"Sabrina Binti Ali Khan - Tiket # 89",
"Salliana Sgawi - Tiket # 189",
"Salmah Binti Saleh - Tiket # 54",
"Salmah binti Salman - Tiket # 147",
"Salwa Binti Maliki @ Razali - Tiket # 151",
"Salwa Binti Ramli - Tiket # 119",
"Serina `Ain Hasmah Shamsuddin - Tiket # 218",
"Shafiqah Binti Zainal Abidin - Tiket # 158",
"Siti Aishah Derani - Tiket # 99",
"Siti Asah Binti Md Ali - Tiket # 135",
"Siti Azizah Binti Mohd Samsudin - Tiket # 176",
"Siti Azzah - Tiket # 226",
"Siti Badariah Binti Ismail - Tiket # 150",
"Siti Fadhlina Halipah - Tiket # 236",
"Siti Fatimah Binti Md Yunus - Tiket # 229",
"Siti Hajar Kamaruddin - Tiket # 220",
"Siti Harlina Binti Abdul Rauf - Tiket # 211",
"Siti Khadijah Binti Mohamed Samsudin - Tiket # 141",
"Siti khaulah binti awai - Tiket # 178",
"Siti Mariani Binti Mior Hasan - Tiket # 96",
"Siti Nor Asniza Binti Kamaruzaman - Tiket # 52",
"Siti Nor Azimah Ibrahim - Tiket # 156",
"Siti norhafeeza hani binti md shukri - Tiket # 100",
"Siti Nurba'yah Binti Abu Hassim - Tiket # 85",
"Siti Nurmahirah Binti Amran - Tiket # 70",
"Siti Nurul Azzua Binti Tamjis - Tiket # 15",
"Siti Shawalriah Binti Mohamad Ab. Jamil - Tiket # 17",
"Siti Zuraida Binti Kadir - Tiket # 83",
"Suhana Shaari - Tiket # 73",
"Sukinah binti Mat Darus - Tiket # 69",
"Suraya binti Baharun - Tiket # 27",
"Suriani Bt Ahmad - Tiket # 111",
"Suriati binti Mohd Desa - Tiket # 153",
"Suriati bt Abdullah - Tiket # 129",
"Suzana Abd Samad - Tiket # 66",
"Syamsiah bt Abd Ghani - Tiket # 184",
"Syaza Nadhirah Ahmad Sabri - Tiket # 235",
"Syazriha Binti Abdul Hanif - Tiket # 91",
"Syuhada Ishak - Tiket # 110",
"Tanty Darwinna Abdull Rahman - Tiket # 239",
"Wan Shahira Binti Wan Ahmad Zaiki - Tiket # 19",
"Zafidah Zainal Abidin - Tiket # 139",
"Zahidah Binti Ismail - Tiket # 131",
"Zainab Binti Saidin - Tiket # 145",
"Zainorhuda Binti Zainal Rashid - Tiket # 210",
"Zarinah Binti Daeman - Tiket # 92",
"Zuraida Binti Zainol - Tiket # 114",
"Zuraidah Binti Ismail - Tiket # 191",
"Zuraini Abdullah Halim - Tiket # 5",
"Zurina Binti Hussin - Tiket # 32"];

function stopRoll() {
    greeting.innerHTML = 'Tahniah Kepada Peserta Bernama'
    var rand = myArray[Math.floor(Math.random() * myArray.length)]; nama.innerHTML = '<strong>' + rand + '</strong> !!!';
}
function resetNama() {
    nama.innerHTML = '<h2 class="alert alert-info" role="alert">Siapakah peserta bertuah yang menghadiri Zumba LAMPU 2016 pada hari ini?</h2>';
}

function roll() {
    var ct = $("#nama").data("term") || 0;
    $("#nama").data("term", ct == myArray.length - 1 ? 0 : Math.floor(Math.random() * myArray.length)).text(myArray[ct]).fadeIn(200).fadeOut(200, roll);
}
