var myArray = ["Noraziah Binti M Roshid",
"Nadya Nikman",
"Norazwana Binti Aizon",
"Afina Razla Binti Afifuddin",
"Zuraini Abdullah Halim",
"Hazimah Binti Mustafa",
"Nazira mustafa",
"Emmi Nur Sila Binti Adnan",
"Norhaliza Binti Abu Bakar",
"Nurseha Binti Ramlee",
"Azlin Hafiza Binti Abd Aziz",
"Nor Hanisah Binti Ishak",
"Hazizah Binti Abdullah",
"Norhatini Binti Idris",
"Siti Nurul Azzua Binti Tamjis",
"Norliana Akida Binti Abd Rahim",
"Siti Shawalriah Binti Mohamad Ab. Jamil",
"Maryam Nazeera Binti Suhaimi ",
"Wan Shahira Binti Wan Ahmad Zaiki",
"Norzalillah Binti Abdullah",
"Noorainura Binti Mazlan",
"Nur Aqilah Binti Shamsuddin",
"Noraidah Binti Dolah",
"Norliza Binti Bahsin@Zakaria",
"Nor Diana Binti Yahaya",
"Azmiza Binti Hamzah",
"Suraya binti Baharun",
"Ezenti Rubiyani Binti Ismail",
"Nur Huda Binti Abdul Hamid",
"Hasnira Binti Hassan",
"Maizatul Natrah binti Mohd Rusdi",
"Zurina Binti Hussin",
"Nur Hafiza Binti Muhammad Azhari",
"Ezan Zailah Binti Rahim",
"Julia Binti Abdul Razak",
"Azlinda Binti Alies",
"Marshitah Binti Omar",
"Nurul Izzah Binti Mohd Yusof",
"Herdawaty Binti Atan",
"Norida Saidi Binti Abd Manaf",
"Amy Nur Diyana Binti Mohamed Nasir",
"Nur Azera Binti Mohamad",
"Ku Azma Liza Bt Ku Abd Hamid",
"Nurul Aini Fazillah Binti Ahmad Taufik",
"Munirah Binti Osri",
"Isma Hamiza Binti Ismail",
"Nur Asmira Binti Asmat",
"Mahizah Binti Mat Zain",
"Norazrena Binti Halim",
"Rohanizawati Binti Hasni",
"Nurul Ain Shafini Binti Abdul Khalid",
"Siti Nor Asniza Binti Kamaruzaman",
"Fauzani Binti Azam",
"Salmah Binti Saleh",
"Azmaliza Binti Khamis",
"Nur Hidayah Binti Abdul Raub",
"Nur Halinna Binti Abdul Rahman",
"Fadzilah Binti Salimin",
"Noran Najmi Rosmi",
"Insaliza Binti Waslan",
"Mazuin Binti Masuaud",
"Fatin Ajla Binti Khairy",
"Nurul Asyilah Binti Mohd Khalid",
"Rus Ima Nadia Binti Hussain",
"Athiah bt Mohd Hassan",
"Noraini binti Nazrin",
"Juliyana Binti Burhan",
"Nurul Hanim Zainudin",
"Sukinah binti Mat Darus",
"Wan Fathiyah",
"Farahwahida Binti Anuar",
"Wan Nor Afni Binti Wan Mustama",
"Suhana Shaari",
"Fauziah binti Adam",
"Norwahida bt Shuib",
"Nurzulyna Binti Sani",
"Dr. Norizah Binti Hj Ibrahim",
"Norhamsiah Baharuddin",
"Nurul Hidayah Binti Mohamad@Mohd Khalid",
"Nor Haslinda Mohd Harun",
"Shairatul Zawani Binti Mohd Jaffar",
"Fitriani Bakthiar",
"Siti Zuraida Binti Kadir",
"Nuraisyah Binti Abu Hassim",
"Siti Nurba'yah Binti Abu Hassim",
"Norliza Binti Hood",
"Nor Aziela Jamaluddin",
"Nurhayati Binti Mohd Wahid",
"Sabrina Binti Ali Khan",
"Nur Azianni Binti Abd Aziz",
"Syazriha Binti Abdul Hanif",
"Zarinah Binti Daeman",
"Nurhuwaina Bt Mohd Afandi",
"Nurul 'Aliaa Binti Nik Zulkipli",
"Hafezatul Nadia Binti Musthafa",
"Siti Mariani Binti Mior Hasan",
"Noor Hafizoh Binti Saebon",
"Asmawati Binti Samsul",
"Siti Aishah Derani",
"Nor Amira Binti Othman",
"Nuramimah Binti Azahar",
"Azida Kama Binti Azmir",
"Nor Asikin Bt Ab Razak",
"Nurrul Hafizah",
"Intan Hafina",
"Intan Annisa",
"Fadhlul Jannah Abd Karim",
"Aini Yusnina Mohamad Yusop",
"Anul Suhada Abu Bakar",
"Syuhada Ishak",
"Suriani Bt Ahmad",
"Nazirah bt Abdullah",
"Noor Azrin bt Abdul Wahab",
"Zuraida Binti Zainol",
"Normala Hanim binti Abdul Hamid",
"Khairun Nisa Binti Bahari",
"Nor Hafizah Bt Zainol",
"Noraini binti Talib",
"Salwa Binti Ramli",
"Nur Aimuni Athirah Binti Omar",
"Ezrina Fairuz Binti Mat Isa",
"Norakmal Binti Mohd Punzan",
"Hafiza",
"Hasnah Binti Ghazali",
"Nor Azimah Binti Jamaluddin",
"Noor Munirah Binti Zainol Abidin",
"Norshimah Shahrudin",
"Rosmawar binti Mahadi",
"Suriati bt Abdullah",
"Che Wan Rohata Binti Abdul Hamid",
"Zahidah Binti Ismail",
"Rizaiton Binti Khairuddin",
"Faridatul Najihah Binti Muhamad Ali",
"Marina Binti Mansor",
"Siti Asah Binti Md Ali",
"Nor Diana Bt Azlan",
"Mardiah Mohamed Saleh",
"Khalidah Adibah Khalid",
"Zafidah Zainal Abidin",
"Fara Shafiza Othman",
"Nor Hafidzah Binti Zainuddin",
"Masni Binti Mohd Marzuki",
"Nor Azlan Binti Atan",
"Nur Malina bt Che Mohd Sukarhata",
"Zainab Binti Saidin",
"Nur Hidayatul Akhmal",
"Salmah binti Salman",
"Khatijah Binti Mohd",
"Kushamsinar",
"Siti Badariah Binti Ismail",
"Salwa Binti Maliki @ Razali",
"Nor Azuma Binti Che Azmi",
"Suriati binti Mohd Desa",
"Rohaya Binti Mohd Yasin",
"Puteri Alia Qamareena Zulkifle",
"Siti Nor Azimah Ibrahim",
"Nur Ruzanna Binti Mohamad Allias",
"Liyana Binti Mat Rani",
"Norhayati Binti Abd Malik",
"Noraishah Rahimah Binti Omar",
"Rahimah Binti Saidin",
"Norhairiza Binti Mohd Ridzan",
"Noraliza Binti Abdul Hamid",
"Haslinda binti Md Yatim",
"Asma Amira",
"Azzura binti Abd Latif",
"Haryana Abdul Rahim",
"Dr Intan Safinaz binti Zainudin",
"Nur Sabrina binti Amran",
"Putri Amilia (Puan Norzita)",
"Siti Noor Adilah Bt Bahrin",
"Nor Hidayu Binti Abdul Halim",
"Noraini Binti Mat Isa",
"Norfaraziana Binti Minhat",
"Siti Aishah binti Mohd Noor",
"Siti Azizah Binti Mohd Samsudin",
"Zubaidah Binti Jamaludin",
"Walafeda Abdullah",
"Nurulnikmah Sukaimi",
"Ani Bt Abdullah",
"Suhanah Bt Kassiron",
"Rose Nur Faezah binti Yusop",
"Hadiana Binti Ishak",
"Syamsiah bt Abd Ghani",
"Nor Mah Ahmad",
"Ainol Mardhiah Binti Mohd Khalid",
"Norfaizah Binti Ghazaly",
"Noor Hafidza by. Sajuni",
"Salliana Sgawi",
"Marsyila Binti Masrom",
"Zuraidah Binti Ismail",
"Azmah Binti Hamzah",
"Norsuzira Binti Setia",
"Noor Juliana Binti Mohamad Jamal",
"Diana Binti Seman",
"Nordiana Binti Rozali",
"Rohaidah Binti Mad Said",
"Nor Haslina Muhamad",
"Norzaihan Binti Rohman",
"Zainorhuda Binti Zainal Rashid",
"Siti Harlina Binti Abdul Rauf",
"Nurullizah Binti Jamaludin",
"Intan Rayahin Bt. Hassan",
"Nur Ain Bt Idris",
"Ruzana Che Soh",
"Serina `Ain Hasmah Shamsuddin",
"Habibah Bt Abdul Shukor",
"Siti Hajar Kamaruddin",
"Nuurul Aqmar Bt Ali",
"Nor Azliza Rahman",
"Nor Hafizah Bt. Hashim",
"Nora Azila Baharudin",
"Nurul Syafiqah Halim",
"Nur Ita Jusnita Binti Rusli",
"Aida Farisa",
"Sufyyatul Azzalina Binti Nasri",
"Siti Fatimah Binti Md Yunus",
"Elena Sofia Elfera Mamat",
"Nurul Asyekin Ismail",
"Norhaliza binti Hanifah",
"Masitah Bt Mustapha ",
"Nur `Izzan Fariha Ahmad Sabri",
"Syaza Nadhirah Ahmad Sabri",
"Siti Fadhlina Halipah",
"Poniah binti Badrul",
"Aimi Syazwani Binti Zainuddin",
"Tanty Darwinna Abdull Rahman",
"Nur Alia Binti Zarmani",
"Farziliyatul Ashmar Izahar",
"Norain Shakira Binti Mohd Salleh",
"Nur Adibah Nabilah Binti Abu Bakar",
"Mimi Suzana Bt Mohd Rashid",
"Nor Khairunnisa Bt Johari",
"Nurul Mardhiah Bt Mohammed Redza",
"Nor Aziati Jaafar",
"Maheran Binti Kasim",
"Mazliza Bt Abdul Wahid"];

function stopRoll() {
    greeting.innerHTML = 'Tahniah Kepada Peserta Bernama'
    var rand = myArray[Math.floor(Math.random() * myArray.length)]; nama.innerHTML = '<strong>' + rand + '</strong> !!!';
}
function resetNama() {
    nama.innerHTML = '<h2 class="alert alert-info" role="alert">Siapakah peserta bertuah yang menghadiri Zumba LAMPU 2016 pada hari ini?</h2>';
}

function roll() {
    var ct = $("#nama").data("term") || 0;
    $("#nama").data("term", ct == myArray.length - 1 ? 0 : Math.floor(Math.random() * myArray.length)).text(myArray[ct]).fadeIn(200).fadeOut(200, roll);
}
