var myArray = ["Noraziah Binti M Roshid - Tiket #  1",
"Nadya Nikman - Tiket #  2",
"Norazwana Binti Aizon - Tiket #  3",
"Afina Razla Binti Afifuddin - Tiket #  4",
"Zuraini Abdullah Halim - Tiket #  5",
"Hazimah Binti Mustafa - Tiket #  6",
"Nazira mustafa - Tiket #  7",
"Emmi Nur Sila Binti Adnan - Tiket #  8",
"Norhaliza Binti Abu Bakar - Tiket #  9",
"Nurseha Binti Ramlee - Tiket #  10",
"Azlin Hafiza Binti Abd Aziz - Tiket #  11",
"Nor Hanisah Binti Ishak - Tiket #  12",
"Hazizah Binti Abdullah - Tiket #  13",
"Norhatini Binti Idris - Tiket #  14",
"Siti Nurul Azzua Binti Tamjis - Tiket #  15",
"Norliana Akida Binti Abd Rahim - Tiket #  16",
"Siti Shawalriah Binti Mohamad Ab. Jamil - Tiket #  17",
"Maryam Nazeera Binti Suhaimi  - Tiket #  18",
"Wan Shahira Binti Wan Ahmad Zaiki - Tiket #  19",
"Norzalillah Binti Abdullah - Tiket #  20",
"Noorainura Binti Mazlan - Tiket #  21",
"Nur Aqilah Binti Shamsuddin - Tiket #  22",
"Noraidah Binti Dolah - Tiket #  23",
"Norliza Binti Bahsin@Zakaria - Tiket #  24",
"Nor Diana Binti Yahaya - Tiket #  25",
"Azmiza Binti Hamzah - Tiket #  26",
"Suraya binti Baharun - Tiket #  27",
"Ezenti Rubiyani Binti Ismail - Tiket #  28",
"Nur Huda Binti Abdul Hamid - Tiket #  29",
"Hasnira Binti Hassan - Tiket #  30",
"Maizatul Natrah binti Mohd Rusdi - Tiket #  31",
"Zurina Binti Hussin - Tiket #  32",
"Nur Hafiza Binti Muhammad Azhari - Tiket #  33",
"Ezan Zailah Binti Rahim - Tiket #  34",
"Julia Binti Abdul Razak - Tiket #  35",
"Azlinda Binti Alies - Tiket #  36",
"Marshitah Binti Omar - Tiket #  37",
"Nurul Izzah Binti Mohd Yusof - Tiket #  38",
"Herdawaty Binti Atan - Tiket #  39",
"Norida Saidi Binti Abd Manaf - Tiket #  40",
"Amy Nur Diyana Binti Mohamed Nasir - Tiket #  41",
"Nur Azera Binti Mohamad - Tiket #  42",
"Ku Azma Liza Bt Ku Abd Hamid - Tiket #  43",
"Nurul Aini Fazillah Binti Ahmad Taufik - Tiket #  44",
"Munirah Binti Osri - Tiket #  45",
"Isma Hamiza Binti Ismail - Tiket #  46",
"Nur Asmira Binti Asmat - Tiket #  47",
"Mahizah Binti Mat Zain - Tiket #  48",
"Norazrena Binti Halim - Tiket #  49",
"Rohanizawati Binti Hasni - Tiket #  50",
"Nurul Ain Shafini Binti Abdul Khalid - Tiket #  51",
"Siti Nor Asniza Binti Kamaruzaman - Tiket #  52",
"Fauzani Binti Azam - Tiket #  53",
"Salmah Binti Saleh - Tiket #  54",
"Azmaliza Binti Khamis - Tiket #  55",
"Nur Hidayah Binti Abdul Raub - Tiket #  56",
"Nur Halinna Binti Abdul Rahman - Tiket #  57",
"Fadzilah Binti Salimin - Tiket #  58",
"Noran Najmi Rosmi - Tiket #  59",
"Insaliza Binti Waslan - Tiket #  60",
"Mazuin Binti Masuaud - Tiket #  61",
"Fatin Ajla Binti Khairy - Tiket #  62",
"Nurul Asyilah Binti Mohd Khalid - Tiket #  63",
"Rus Ima Nadia Binti Hussain - Tiket #  64",
"Athiah bt Mohd Hassan - Tiket #  65",
"Noraini binti Nazrin - Tiket #  66",
"Juliyana Binti Burhan - Tiket #  67",
"Nurul Hanim Zainudin - Tiket #  68",
"Sukinah binti Mat Darus - Tiket #  69",
"Wan Fathiyah - Tiket #  70",
"Farahwahida Binti Anuar - Tiket #  71",
"Wan Nor Afni Binti Wan Mustama - Tiket #  72",
"Suhana Shaari - Tiket #  73",
"Fauziah binti Adam - Tiket #  74",
"Norwahida bt Shuib - Tiket #  75",
"Nurzulyna Binti Sani - Tiket #  76",
"Dr. Norizah Binti Hj Ibrahim - Tiket #  77",
"Norhamsiah Baharuddin - Tiket #  78",
"Nurul Hidayah Binti Mohamad@Mohd Khalid - Tiket #  79",
"Nor Haslinda Mohd Harun - Tiket #  80",
"Shairatul Zawani Binti Mohd Jaffar - Tiket #  81",
"Fitriani Bakthiar - Tiket #  82",
"Siti Zuraida Binti Kadir - Tiket #  83",
"Nuraisyah Binti Abu Hassim - Tiket #  84",
"Siti Nurba'yah Binti Abu Hassim - Tiket #  85",
"Norliza Binti Hood - Tiket #  86",
"Nor Aziela Jamaluddin - Tiket #  87",
"Nurhayati Binti Mohd Wahid - Tiket #  88",
"Sabrina Binti Ali Khan - Tiket #  89",
"Nur Azianni Binti Abd Aziz - Tiket #  90",
"Syazriha Binti Abdul Hanif - Tiket #  91",
"Zarinah Binti Daeman - Tiket #  92",
"Nurhuwaina Bt Mohd Afandi - Tiket #  93",
"Nurul 'Aliaa Binti Nik Zulkipli - Tiket #  94",
"Hafezatul Nadia Binti Musthafa - Tiket #  95",
"Siti Mariani Binti Mior Hasan - Tiket #  96",
"Noor Hafizoh Binti Saebon - Tiket #  97",
"Asmawati Binti Samsul - Tiket #  98",
"Siti Aishah Derani - Tiket #  99",
"Nor Amira Binti Othman - Tiket #  100",
"Nuramimah Binti Azahar - Tiket #  101",
"Azida Kama Binti Azmir - Tiket #  102",
"Nor Asikin Bt Ab Razak - Tiket #  103",
"Nurrul Hafizah - Tiket #  104",
"Intan Hafina - Tiket #  105",
"Intan Annisa - Tiket #  106",
"Fadhlul Jannah Abd Karim - Tiket #  107",
"Aini Yusnina Mohamad Yusop - Tiket #  108",
"Anul Suhada Abu Bakar - Tiket #  109",
"Syuhada Ishak - Tiket #  110",
"Suriani Bt Ahmad - Tiket #  111",
"Nazirah bt Abdullah - Tiket #  112",
"Noor Azrin bt Abdul Wahab - Tiket #  113",
"Zuraida Binti Zainol - Tiket #  114",
"Normala Hanim binti Abdul Hamid - Tiket #  115",
"Khairun Nisa Binti Bahari - Tiket #  116",
"Nor Hafizah Bt Zainol - Tiket #  117",
"Noraini binti Talib - Tiket #  118",
"Salwa Binti Ramli - Tiket #  119",
"Nur Aimuni Athirah Binti Omar - Tiket #  120",
"Ezrina Fairuz Binti Mat Isa - Tiket #  121",
"Norakmal Binti Mohd Punzan - Tiket #  122",
"Hafiza - Tiket #  123",
"Hasnah Binti Ghazali - Tiket #  124",
"Nor Azimah Binti Jamaluddin - Tiket #  125",
"Noor Munirah Binti Zainol Abidin - Tiket #  126",
"Norshimah Shahrudin - Tiket #  127",
"Rosmawar binti Mahadi - Tiket #  128",
"Suriati bt Abdullah - Tiket #  129",
"Che Wan Rohata Binti Abdul Hamid - Tiket #  130",
"Zahidah Binti Ismail - Tiket #  131",
"Rizaiton Binti Khairuddin - Tiket #  132",
"Faridatul Najihah Binti Muhamad Ali - Tiket #  133",
"Marina Binti Mansor - Tiket #  134",
"Siti Asah Binti Md Ali - Tiket #  135",
"Nor Diana Bt Azlan - Tiket #  136",
"Mardiah Mohamed Saleh - Tiket #  137",
"Khalidah Adibah Khalid - Tiket #  138",
"Zafidah Zainal Abidin - Tiket #  139",
"Fara Shafiza Othman - Tiket #  140",
"Nor Hafidzah Binti Zainuddin - Tiket #  141",
"Masni Binti Mohd Marzuki - Tiket #  142",
"Nor Azlan Binti Atan - Tiket #  143",
"Nur Malina bt Che Mohd Sukarhata - Tiket #  144",
"Zainab Binti Saidin - Tiket #  145",
"Nur Hidayatul Akhmal - Tiket #  146",
"Salmah binti Salman - Tiket #  147",
"Khatijah Binti Mohd - Tiket #  148",
"Kushamsinar - Tiket #  149",
"Siti Badariah Binti Ismail - Tiket #  150",
"Salwa Binti Maliki @ Razali - Tiket #  151",
"Nor Azuma Binti Che Azmi - Tiket #  152",
"Suriati binti Mohd Desa - Tiket #  153",
"Rohaya Binti Mohd Yasin - Tiket #  154",
"Puteri Alia Qamareena Zulkifle - Tiket #  155",
"Siti Nor Azimah Ibrahim - Tiket #  156",
"Nur Ruzanna Binti Mohamad Allias - Tiket #  157",
"Liyana Binti Mat Rani - Tiket #  158",
"Norhayati Binti Abd Malik - Tiket #  159",
"Noraishah Rahimah Binti Omar - Tiket #  160",
"Rahimah Binti Saidin - Tiket #  161",
"Norhairiza Binti Mohd Ridzan - Tiket #  162",
"Noraliza Binti Abdul Hamid - Tiket #  163",
"Haslinda binti Md Yatim - Tiket #  164",
"Asma Amira - Tiket #  165",
"Azzura binti Abd Latif - Tiket #  166",
"Haryana Abdul Rahim - Tiket #  167",
"Dr Intan Safinaz binti Zainudin - Tiket #  168",
"Nur Sabrina binti Amran - Tiket #  169",
"Putri Amilia (Puan Norzita) - Tiket #  170",
"Siti Noor Adilah Bt Bahrin - Tiket #  171",
"Nor Hidayu Binti Abdul Halim - Tiket #  172",
"Noraini Binti Mat Isa - Tiket #  173",
"Norfaraziana Binti Minhat - Tiket #  174",
"Siti Aishah binti Mohd Noor - Tiket #  175",
"Siti Azizah Binti Mohd Samsudin - Tiket #  176",
"Zubaidah Binti Jamaludin - Tiket #  177",
"Walafeda Abdullah - Tiket #  178",
"Nurulnikmah Sukaimi - Tiket #  179",
"Ani Bt Abdullah - Tiket #  180",
"Suhanah Bt Kassiron - Tiket #  181",
"Rose Nur Faezah binti Yusop - Tiket #  182",
"Hadiana Binti Ishak - Tiket #  183",
"Syamsiah bt Abd Ghani - Tiket #  184",
"Nor Mah Ahmad - Tiket #  185",
"Ainol Mardhiah Binti Mohd Khalid - Tiket #  186",
"Norfaizah Binti Ghazaly - Tiket #  187",
"Noor Hafidza by. Sajuni - Tiket #  188",
"Salliana Sgawi - Tiket #  189",
"Marsyila Binti Masrom - Tiket #  190",
"Zuraidah Binti Ismail - Tiket #  191",
"Azmah Binti Hamzah - Tiket #  192",
"Norsuzira Binti Setia - Tiket #  193",
"Noor Juliana Binti Mohamad Jamal - Tiket #  194",
"Diana Binti Seman - Tiket #  195",
"Sponsor (Tiket Free) - Tiket #  196",
"Sponsor (Tiket Free) - Tiket #  197",
"Sponsor (Tiket Free) - Tiket #  198",
"Sponsor (Tiket Free) - Tiket #  199",
"Sponsor (Tiket Free) - Tiket #  200",
"Sponsor (Tiket Free) - Tiket #  201",
"Sponsor (Tiket Free) - Tiket #  202",
"Sponsor (Tiket Free) - Tiket #  203",
"Sponsor (Tiket Free) - Tiket #  204",
"Sponsor (Tiket Free) - Tiket #  205",
"Nordiana Binti Rozali - Tiket #  206",
"Rohaidah Binti Mad Said - Tiket #  207",
"Nor Haslina Muhamad - Tiket #  208",
"Norzaihan Binti Rohman - Tiket #  209",
"Zainorhuda Binti Zainal Rashid - Tiket #  210",
"Siti Harlina Binti Abdul Rauf - Tiket #  211",
"Nurullizah Binti Jamaludin - Tiket #  212",
"Intan Rayahin Bt. Hassan - Tiket #  213",
" - Tiket #  214",
"Nur Ain Bt Idris - Tiket #  215",
" - Tiket #  216",
"Ruzana Che Soh - Tiket #  217",
"Serina `Ain Hasmah Shamsuddin - Tiket #  218",
"Habibah Bt Abdul Shukor - Tiket #  219",
"Siti Hajar Kamaruddin - Tiket #  220",
"Nuurul Aqmar Bt Ali - Tiket #  221",
"Nor Azliza Rahman - Tiket #  222",
"Nor Hafizah Bt. Hashim - Tiket #  223",
"Nora Azila Baharudin - Tiket #  224",
"Nurul Syafiqah Halim - Tiket #  225",
"Nur Ita Jusnita Binti Rusli - Tiket #  226",
"Aida Farisa - Tiket #  227",
"Sufyyatul Azzalina Binti Nasri - Tiket #  228",
"Siti Fatimah Binti Md Yunus - Tiket #  229",
"Elena Sofia Elfera Mamat - Tiket #  230",
"Nurul Asyekin Ismail - Tiket #  231",
"Norhaliza binti Hanifah - Tiket #  232",
"Masitah Bt Mustapha  - Tiket #  233",
"Nur `Izzan Fariha Ahmad Sabri - Tiket #  234",
"Syaza Nadhirah Ahmad Sabri - Tiket #  235",
"Siti Fadhlina Halipah - Tiket #  236",
"Poniah binti Badrul - Tiket #  237",
"Aimi Syazwani Binti Zainuddin - Tiket #  238",
"Tanty Darwinna Abdull Rahman - Tiket #  239",
"Nur Alia Binti Zarmani - Tiket #  240",
"Farziliyatul Ashmar Izahar - Tiket #  241",
" - Tiket #  242",
"Norain Shakira Binti Mohd Salleh - Tiket #  243",
"Nur Adibah Nabilah Binti Abu Bakar - Tiket #  244",
"Mimi Suzana Bt Mohd Rashid - Tiket #  245",
"Nor Khairunnisa Bt Johari - Tiket #  246",
"Nurul Mardhiah Bt Mohammed Redza - Tiket #  247",
"Nor Aziati Jaafar - Tiket #  248",
"Maheran Binti Kasim - Tiket #  249",
"Mazliza Bt Abdul Wahid - Tiket #  250"];

function stopRoll() {
    greeting.innerHTML = 'Tahniah Kepada Peserta Bernama'
    var rand = myArray[Math.floor(Math.random() * myArray.length)]; nama.innerHTML = '<strong>' + rand + '</strong> !!!';
}
function resetNama() {
    nama.innerHTML = '<h2 class="alert alert-info" role="alert">Siapakah peserta bertuah yang menghadiri Zumba LAMPU 2016 pada hari ini?</h2>';
}

function roll() {
    var ct = $("#nama").data("term") || 0;
    $("#nama").data("term", ct == myArray.length - 1 ? 0 : Math.floor(Math.random() * myArray.length)).text(myArray[ct]).fadeIn(200).fadeOut(200, roll);
}
